### ISSUE TITLE
Cannot append to mailbox folder when mailbox name contains spaces

### ISSUE THREAD

**Issue by amitailanciano** [zetacomponents/Mail#10]
Found an issue with the imap transport, mailbox names with spaces are not quoted properly in the `append()` method of `imap_transport.php` which causes an error when appending a message to a mailbox:

According to RFC3501, Mailbox Naming (5.1):

`Any character which is one of the atom-specials (see the Formal Syntax) will require that the mailbox name be represented as a quoted string or literal.`

That includes a space:

`atom-specials = "(" / ")" / "{" / SP / CTL / list-wildcards / quoted-specials / resp-specials`

so, the right mailbox string should be:

`"INBOX.folder with spaces"`

I changed the `{$mailbox}` variables to `\"{$mailbox}\"` in the `append()` method in `imap_transport.php` and it works now.

**Comment by derickr** [comment]
This seems to have been fixed with #11, so (finally) closing this issue.
