### ISSUE TITLE
How to fetch an email without marking it read?

### ISSUE THREAD

**Issue by mnapoli** [zetacomponents/Mail#19]
I think I understand the logic behind marking an email as read when you fetch it, but how can I avoid that?

I have seen in the examples that we can use `top` to get the X first characters of the email, but I would like to get it whole. Is that possible?

The only workaround I can see is fetch all emails, and then manually re-flag them as "unread". But if I fetch an already "read" email, I will mark it "unread", which is wrong.

Any solution?

Thanks!

**Comment by derickr** [comment]
Is this still a live issue for you? If not, I will close it in the next few days.

**Comment by mnapoli** [comment]
@derickr it's been a while for me, at the time I built https://github.com/mnapoli/imapi based on Horde's library. Fine to close for me.

**Comment by derickr** [comment]
Cheers. And yes, I know - it's been more than 5 years :-)
