### ISSUE TITLE
Images will not get filtered correctly

### ISSUE THREAD

**Issue by xrow** [zetacomponents/Mail#2]
If the HTML Mime Part will include image tags like

```
<pre>
<img src="myimage.jpg">
</pre>
```

the Mail Component willl woirk correctly.

If there is a image tag with more attributes after the src attribute the PCRE will fail to get the correct file path.

```
<pre>
<img src="myimage.jpg" extraattribute="test">
</pre>
```

**Comment by derickr** [comment]
Is this still a live issue for you? If not, I will close it in the next few days.

**Comment by xrow** [comment]
Hi Derick,

thanks for asking. I think since so much time is passed lets close it. :-) . I just can`t tell anymore. Cheers from Hannover.

**Comment by derickr** [comment]
I figured, it has been 8 years!

cheers,
Derick
