### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by GittiHab** [zetacomponents/Mail#39]
Is there any documentation to this?
Maybe add a Readme, Wiki and/or link to the website for this Repo.

Thank you. I am sure this is a great library :+1:

**Comment by derickr** [comment]
There is a tutorial at https://github.com/zetacomponents/Mail/blob/master/docs/tutorial.txt - which is rendered, including API docs and examples at http://zetacomponents.org/documentation/trunk/Mail/tutorial.html
