### ISSUE TITLE
Force parse text file attachment as file when Content-Disposition: attachment header

### ISSUE THREAD

**Issue by speller** [zetacomponents/Mail#44]
Please add the ability to parse the text file attachment as file when the `Content-Disposition: attachment` header exists for the part. I have a mail with following part configuartion:

```
Content-Type: text/html; name="=?UTF-8?B?Y2hlY2tfcHJpbnQuZG8uaHRtbA==?="
Content-Disposition: attachment
Content-Transfer-Encoding: base64
```

The `createPartParserForHeaders` method tries to parse this attachment as text part of the mail, so it tries to convert its encoding to utf-8 and fails, because it tries to interpret the part as 'us-ascii'. This is the attachment so it has no the encoding headers (actual file encoding can be any multibyte enoding to cause the mail parsing failure). If I set the `ezcMailPartParser::$parseTextAttachmentsAsFiles` to True the entire mail is parsed successfully, but it consists from attachments only, without any body text.

Suggested fix at part_parser.php:170:

```
if (ezcMailPartParser::$parseTextAttachmentsAsFiles === true || isset($headers['Content-Disposition']) && $headers['Content-Disposition'] === 'attachment' )
```

**Comment by speller** [comment]
Corrected fix suggestion:

```
            case 'text':
                if (
                    ezcMailPartParser::$parseTextAttachmentsAsFiles === true ||
                    isset($headers['Content-Disposition']) && explode(';', $headers['Content-Disposition'])[0] === 'attachment'
                ) {
                    $bodyParser = new ezcMailFileParser( $mainType, $subType, $headers );
                }
                else
                {
                    $bodyParser = new ezcMailTextParser( $subType, $headers );
                }
                break;
```

**Comment by speller** [comment]
Any news on this issue?

**Comment by derickr** [comment]
Is this still a live issue for you?
