### ISSUE TITLE
Iconv error on zetacomponents/mail/src/internal/charset_convert.php line 14

### ISSUE THREAD

**Issue by lafonso** [zetacomponents/Mail#50]
The message is
<b>Notice</b>:  iconv(): Detected an illegal character in input string in <b>C:\inetpub\wwwroot\common_libs\vendor\zetacomponents\mail\src\internal\charset_convert.php</b> on line <b>143</b><br />
Than the text part returns empty
I see the original charset is utf8 and the output is utf8 then i made an if before iconv
if($originalCharset=='utf-8')return $text;

Atached is the email that causes the error, i read it from gmail
[mail.txt](https://github.com/zetacomponents/Mail/files/413814/mail.txt)

**Comment by lafonso** [comment]
This happens only running php on windows, on linux it runs smooth.

**Comment by derickr** [comment]
iconv on Windows is slightly different. Perhaps the hints at http://zetacomponents.org/documentation/trunk/Mail/tutorial.html#parsing-iconv-notices might be of any use.
