### ISSUE TITLE
User names and passwords can contain spaces.

### ISSUE THREAD

**Issue by JeffVeit** [zetacomponents/Mail#51]
I'm working with imap, but the same is true of pop3 and smtp... when a user tries to authenticate, user names may contain spaces. That means that for imap, using LOGIN user pass will fail. The solution is to quote the username and password.

For imap in imap_transport.php, the line should become
        $this->connection->sendData( "{$tag} LOGIN \"{$user}\" \"{$password}\"" );

It might be a good idea to only include quotes when $user or $password has spaces.

Tested on gmail and it works as above.

**Comment by derickr** [comment]
You're probably correct that this change needs to be made, but as the test suite is currently not correctly working, I am reluctant to just make this change at this moment.
