### ISSUE TITLE
Notice: iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by alice4work** [zetacomponents/Mail#65]
ezcMailCharsetConverter::convertToUTF8Iconv() 

Notice: iconv(): Detected an illegal character in input string
vendor/zetacomponents/mail/src/internal/charset_convert.php on line 143

This message causes the problem.
```
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit

Alexander Ashmore �
```

**Comment by derickr** [comment]
Hi!

This is documented at http://zetacomponents.org/documentation/trunk/Mail#parsing-iconv-notices

cheers,
Derick
