### ISSUE TITLE
Incompatible regex with PHP 7.3

### ISSUE THREAD

**Issue by mareeo** [zetacomponents/Mail#68]
PHP 7.3 upgrade PCRE to PCRE 2, causing it to be more strict with character ranges. There are two instances of regex which throw the following error in PHP 7.3: "Compilation failed: invalid range in character class at offset 5"

**Comment by mareeo** [comment]
PR submitted: https://github.com/zetacomponents/Mail/pull/69

**Comment by storeman** [comment]
Is there a release expected with this fix?

**Comment by derickr** [comment]
@storeman I had forgotten, but i've just created 1.8.4: https://packagist.org/packages/zetacomponents/mail#1.8.4
