### ISSUE TITLE
ezcMailTools::mimeHeaderEncode Timeout

### ISSUE THREAD

**Issue by skrosoft** [zetacomponents/Mail#71]
Hi,

I had to replace this line:

https://github.com/zetacomponents/Mail/blob/b60e9a543f6c3d9a9ec74452d4ff5736a1c63a77/src/tools.php#L813

By this line:

`$tmpValue = false;`

For some reason, I had a PHP timeout, even with 180 seconds.

**Comment by derickr** [comment]
That doesn't sound like a problem with this package. Can you provide a reproducible case?

**Comment by derickr** [comment]
Closing this, as the requested feedback wasn't provided.
