### ISSUE TITLE
Issue with civicrm-core

### ISSUE THREAD

**Issue by kamilwezyk** [zetacomponents/Mail#72]
while trying to pull composer civicrm-core i get:
civicrm/civicrm-core 5.12.x-dev requires zetacomponents/mail dev-1.7-civi -> no matching package found

**Comment by derickr** [comment]
I think you should report that to CivicCRM, as there is no such version "dev-1.7-civi" defined on this package.

**Comment by kamilwezyk** [comment]
thank you i will
