### ISSUE TITLE
Undefined variable in imap_set.php

### ISSUE THREAD

**Issue by MrGauz** [zetacomponents/Mail#74]
I believe that the lines 224 and 225 in imap_set.php should be swapped as otherwise there is a case in which $data will be returned althought it is not set.

public function getNextLine()
    {   
        if ( $this->hasMoreMailData )
        {
            if ( $this->bytesToRead !== false && $this->bytesToRead >= 0 )
            {
                $data = $this->connection->getLine(); // <- $data is set here
                $this->bytesToRead -= strlen( $data );
                if ( $this->bytesToRead <= 0 )
                {
                    ...
                    return $data;
                }
            }
            return $data; // <- $data is returned outside of if although it might not be set
        }
        return null;
    }

I believe `return $data;` should be inside of if statement.

**Comment by derickr** [comment]
I think there was a PR #73 for this, which I've just merged, so closing this report.
