### ISSUE TITLE
Curly-brace syntax for array and string access is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by sapphirecat** [zetacomponents/Mail#77]
I'm testing the waters for a potential PHP 7.4 upgrade in the future, my unit test suite is failing due to a deprecation warning.

Specifically, [line 108 of src/tools.php](https://github.com/zetacomponents/Mail/blob/5205b2c23c03946d688271027256495215a816fc/src/tools.php#L108) uses `$name{0}` etc.  I haven't looked around for any other usages like this.

The deprecation message is "PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in …/vendor/zetacomponents/mail/src/tools.php on line 108"

zetacomponents/mail is at 1.8.4 which is the latest available release AFAIK.

**Comment by derickr** [comment]
Fixed. Thanks for letting me know!
